### ISSUE TITLE
$HOME path is hardcoded in most of the scripts

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/softcut-studies#1]
For example https://github.com/monome/softcut-studies/blob/master/5-filters.lua#L9

@tehn What would be the correct way of fixing this?
I'd normally say `include`, but that only works for Lua files

**Comment by tehn** [comment]
i need to use the `_path.dust` var which is set in `config.lua`

but that also gets back to `$HOME`

how to do you propose tracking the `dust` location across buildroot/raspbian?

**Comment by simonvanderveldt** [comment]
Using the `$HOME` env car is fine, only hard coded paths are a problem.

**Comment by tehn** [comment]
fixed

**Comment by simonvanderveldt** [comment]
@tehn How can we fix this one? https://github.com/monome/softcut-studies/blob/f559bd694ff1660f2a34fb0283d83a3732e89e2c/3-cut.lua#L6

**Comment by tehn** [comment]
fixed, sorry to have missed it

**Comment by simonvanderveldt** [comment]
No problem at all :)
Thanks for the quick fix!
