### ISSUE TITLE
Common audio no longer available

### ISSUE THREAD

**Issue by barksten** [monome/softcut-studies#5]
https://github.com/monome/softcut-studies/blob/7bc51c5c07b8846d9db3fe1c2039b9566912de2a/2-multi.lua#L7

This doesn't work anymore (at least since 220306). There is no "common" folder installed.

**Comment by tehn** [comment]
accidentally renamed the folder `x0x` for the newest disk image

**Comment by tehn** [comment]
ack, also the waves folder failed to get included

**Comment by dndrks** [comment]
files now hosted here: https://github.com/dndrks/norns-common-audio/releases/tag/common

**Comment by joeweiss** [comment]
I made a PR for this issue. Just copied the missing wav file into `lib`, and updated 2-multi.lua. 
Thanks for the studies! I'm working through them now. Good stuff.
